src/EndPoints/DigiLearn.Web/Areas/Admin/Pages/Courses/Categories/Edit.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;
using CoreModule.Application.Category.Edit;
using CoreModule.Facade.Category;
using BTCsalman.Web.Infrastructure.RazorUtils;

namespace BTCsalman.Web.Areas.Admin.Pages.Courses.Categories
{
    [BindProperties]
    public class EditModel : BaseRazor
    {
        private ICourseCategoryFacade _categoryFacade;

        public EditModel(ICourseCategoryFacade categoryFacade)
        {
            _categoryFacade = categoryFacade;
        }

        [Display(Name = "عنوان")]
        [Required(ErrorMessage = "{0} را وارد کنید")]
        public string Title { get; set; }

        [Display(Name = "عنوان انگلیسی")]
        [Required(ErrorMessage = "{0} را وارد کنید")]
        public string Slug { get; set; }
        public async Task<IActionResult> OnGet(Guid id)
        {
            var category = await _categoryFacade.GetById(id);
            if (category == null)
                return RedirectToPage("Index");


            Title = category.Title;
            Slug = category.Slug;
            return Page();
        }

        public async Task<IActionResult> OnPost(Guid id)
        {
            var result = await _categoryFacade.Edit(new EditCategoryCommand()
            {
                Slug = Slug,
                Title = Title,
                Id = id
            });
            return RedirectAndShowAlert(result, RedirectToPage("Index"));
        }
    }
}

src/EndPoints/DigiLearn.Web/Areas/Admin/Pages/Courses/Edit.cshtml.cs
using System.ComponentModel.DataAnnotations;
using Common.Application;
using Common.Domain.ValueObjects;
using CoreModule.Application.Course.Edit;
using CoreModule.Domain.Course.Enums;
using CoreModule.Facade.Course;
using BTCsalman.Web.Infrastructure.RazorUtils;
using BTCsalman.Web.Infrastructure.Utils.CustomValidation.IFormFile;
using BTCsalman.Web.Infrastructure.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BTCsalman.Web.Areas.Admin.Pages.Courses
{

    [BindProperties]
    public class EditModel : BaseRazor
    {
        private readonly ICourseFacade _courseFacade;

        public EditModel(ICourseFacade courseFacade)
        {
            _courseFacade = courseFacade;
        }


        public Guid CategoryId { get; set; }
        public Guid SubCategoryId { get; set; }

        [Display(Name = "عنوان")]
        [Required(ErrorMessage = "{0} را وارد کنید")]
        public string Title { get; set; }

        [Display(Name = "عنوان انگلیسی")]
        [Required(ErrorMessage = "{0} را وارد کنید")]
        public string Slug { get; set; }

        [Display(Name = "توضیحات")]
        [Required(ErrorMessage = "{0} را وارد کنید")]
        [UIHint("Ckeditor4")]
        public string Description { get; set; }


        [Display(Name = "عکس")]
        [FileImage(ErrorMessage = "عکس نامعتبر است")]
        public IFormFile? ImageFile { get; set; }

        [Display(Name = "ویدئو معرفی")]
        [FileType("mp4", ErrorMessage = "ویدئو معرفی نامعتبر است")]
        public IFormFile? VideoFile { get; set; }


        [Display(Name = "قیمت")]
        public int Price { get; set; }
        public SeoDataViewModel SeoData { get; set; }



        [Display(Name = "سطح دوره")]
        public CourseLevel CourseLevel { get; set; }


        [Display(Name = "وضعیت دوره")]
        public CourseStatus CourseStatus { get; set; }


        [Display(Name = "وضعیت")]
        public CourseActionStatus ActionStatus { get; set; }

        public async Task<IActionResult> OnGet(Guid courseId)
        {
            var course = await _courseFacade.GetCourseById(courseId);


            if (course == null)
                return RedirectToPage("Index");


            CategoryId = course.CategoryId;
            SubCategoryId = course.SubCategoryId;
            Title = course.Title;
            Slug = course.Slug;
            Description = course.Description;
            SeoData = SeoDataViewModel.ConvertToViewModel(course.SeoData);
            CourseLevel = course.CourseLevel;
            CourseStatus = course.CourseStatus;
            ActionStatus = course.Status;

            return Page();
        }

        public async Task<IActionResult> OnPost(Guid courseId)
        {
            var result = await _courseFacade.Edit(new EditCourseCommand
            {
                CourseId = courseId,
                CategoryId = CategoryId,
                SubCategoryId = SubCategoryId,
                Title = Title,
                Slug = Slug,
                Description = Description,
                ImageFile = ImageFile,
                VideoFile = VideoFile,
                Price = Price,
                SeoData = SeoData.Map(),
                CourseLevel = CourseLevel,
                CourseStatus = CourseStatus,
                CourseActionStatus = ActionStatus
            });
            return RedirectAndShowAlert(result, RedirectToPage("Index"));
        }
    }
}

src/EndPoints/DigiLearn.Web/Areas/Admin/Pages/Roles/Index.cshtml.cs
using System.ComponentModel.DataAnnotations;
using Common.Application;
using BTCsalman.Web.Infrastructure.RazorUtils;
using BTCsalman.Web.ViewModels.Admin;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using UserModule.Core.Commands.Roles.Create;
using UserModule.Core.Commands.Roles.Edit;
using UserModule.Core.Services;
using UserModule.Data.Entities._Enums;
using UserModule.Data.Entities.Roles;

namespace BTCsalman.Web.Areas.Admin.Pages.Roles
{
    public class IndexModel : BaseRazor
    {
        private readonly IRoleFacade _roleFacade;
        private IRenderViewToString _renderViewToString;
        public IndexModel(IRoleFacade roleFacade, IRenderViewToString renderViewToString)
        {
            _roleFacade = roleFacade;
            _renderViewToString = renderViewToString;
        }

        [Display(Name = "عنوان")]
        [Required(ErrorMessage = "{0} را وارد کنید")]
        [BindProperty]
        public string Name { get; set; }



        public List<Role> Roles { get; set; }
        public async Task OnGet()
        {
            Roles = await _roleFacade.GetAllRoles();
        }

        public async Task<IActionResult> OnGetShowEditPage(Guid id)
        {
            return await AjaxTryCatch(async () =>
            {
                var role = await _roleFacade.GetRoleById(id);
                if (role == null)
                {
                    return OperationResult<string>.NotFound();
                }
                var view = await _renderViewToString.RenderToStringAsync("_Edit", new EditRoleViewModel()
                {
                    Name = role.Name,
                    RoleId = id,
                    SelectedPermissions = role.Permissions.Select(s => s.Permissions).ToList()
                }, PageContext);
                return OperationResult<string>.Success(view);
            });
        }

        public async Task<IActionResult> OnPostEdit(EditRoleViewModel viewModel, List<Permissions> permissions)
        {
            return await AjaxTryCatch(() => _roleFacade.Edit(new EditRoleCommand()
            {
                Name = viewModel.Name,
                RoleId = viewModel.RoleId,
                Permissions = permissions
            }));
        }
        public async Task<IActionResult> OnPost(List<Permissions> permissions)
        {
            return await AjaxTryCatch(() => _roleFacade.Create(new CreateRoleCommand()
            {
                Name = Name,
                Permissions = permissions
            }));
        }

        public async Task<IActionResult> OnPostDelete(Guid id)
        {
            return await AjaxTryCatch(() => _roleFacade.Delete(id));
        }
    }


}

src/EndPoints/DigiLearn.Web/Areas/Admin/Pages/Users/Edit.cshtml.cs
using System.ComponentModel.DataAnnotations;
using BTCsalman.Web.Infrastructure.RazorUtils;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using UserModule.Core.Commands.Users.FullEdit;
using UserModule.Core.Services;

namespace BTCsalman.Web.Areas.Admin.Pages.Users;



[BindProperties]
public class EditModel : BaseRazor
{
    private IUserFacade _userFacade;

    public EditModel(IUserFacade userFacade)
    {
        _userFacade = userFacade;
    }

    [Display(Name = "نام")]
    public string? Name { get; set; }
    [Display(Name = "نام خانوادگی")]

    public string? Family { get; set; }

    [Display(Name = "ایمیل")]
    [DataType(DataType.EmailAddress)]
    public string? Email { get; set; }

    [Display(Name = "شماره تلفن")]
    [Required(ErrorMessage = "{0} را وارد کنید")]
    public string PhoneNumber { get; set; }


    [Display(Name = "کلمه عبور")]
    [DataType(DataType.Password)]
    public string? Password { get; set; }

    public List<Guid> CurrentUserRoles { get; set; }
    public async Task<IActionResult> OnGet(Guid id)
    {
        var user = await _userFacade.GetById(id);
        if (user == null)
        {
            ErrorAlert("کاربر یافت نشد");
            return RedirectToPage("Index");
        }

        Name = user.Name;
        Family = user.Family;
        Email = user.Email;
        PhoneNumber = user.PhoneNumber;
        CurrentUserRoles = user.Roles.Select(s => s.Id).ToList();
        return Page();
    }

    public async Task<IActionResult> OnPost(Guid id, string[] roles)
    {
        var res = await _userFacade.EditUser(new FullEditUserCommand
        {
            UserId = id,
            Name = Name,
            Family = Family,
            Email = Email,
            PhoneNumber = PhoneNumber,
            Password = Password,
            Roles = roles.Select(Guid.Parse).ToList()
        });
        return RedirectAndShowAlert(res, RedirectToPage("Index"));
    }
}

src/EndPoints/DigiLearn.Web/Pages/Profile/Edit.cshtml.cs
using System.ComponentModel.DataAnnotations;
using BTCsalman.Web.Infrastructure;
using BTCsalman.Web.Infrastructure.RazorUtils;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using UserModule.Core.Commands.Users.Edit;
using UserModule.Core.Services;

namespace BTCsalman.Web.Pages.Profile
{
    [BindProperties]
    public class EditModel : BaseRazor
    {
        private IUserFacade _userFacade;

        public EditModel(IUserFacade userFacade)
        {
            _userFacade = userFacade;
        }

        [Display(Name = "نام")]
        [Required(ErrorMessage = "{0} را وارد کنید")]
        public string Name { get; set; }

        [Display(Name = "نام خانوادگی")]
        [Required(ErrorMessage = "{0} را وارد کنید")]

        public string Family { get; set; }


        [Display(Name = "ایمیل")]
        [Required(ErrorMessage = "{0} را وارد کنید")]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }

        public async Task OnGet()
        {
            var user = await _userFacade.GetUserByPhoneNumber(User.GetPhoneNumber());
            if (user != null)
            {
                Name = user.Name;
                Family = user.Family;
                Email = user.Email;
            }
        }

        public async Task<IActionResult> OnPost()
        {
            var result = await _userFacade.EditUserProfile(new EditUserCommand()
            {
                Name = Name,
                Family = Family,
                Email = Email,
                UserId = User.GetUserId()
            });
            return RedirectAndShowAlert(result, RedirectToPage("Index"));
        }
    }
}

src/EndPoints/DigiLearn.Web/Areas/Admin/Pages/Roles/Index.cshtml
@page "{hander?}"
@using BTCsalman.Web.Infrastructure
@using UserModule.Data.Entities._Enums
@model BTCsalman.Web.Areas.Admin.Pages.Roles.IndexModel
@{
    ViewData["title"] = "مدیریت نقش ها";
    ViewData["selected"] = "roles";
}
<a href="#" data-toggle="modal" data-target="#addModal" class="btn btn-success mb-1">افزودن مورد جدید</a>
<div class="card ">
    <div class="table-responsive card-body p-0 mb-0">
        <table class="table table-bordered table-hover mb-0">
            <thead>
                <tr>
                    <th>عنوان</th>
                    <th>دسترسی ها</th>
                    <th>عملیات</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Roles)
                {
                    <tr>
                        <td>@item.Name</td>
                        <td>
                            @foreach (var per in item.Permissions.Select(s => s.Permissions))
                            {
                                <label class="badge badge-primary">@per.ToString().Replace("_"," ")</label>
                            }
                        </td>
                        <td>
                            <open-modal is-bootstrap4="true" modal-title="ویرایش نقش" class="btn btn-sm btn-primary" url="@Url.Page("Index","ShowEditPage",new {id=item.Id})">ویرایش</open-modal>
                            <delete-item url="@Url.Page("Index","Delete",new {id=item.Id})">حذف</delete-item>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>
<div class="modal fade" id="addModal" tabindex="-1" aria-labelledby="editAddressModalLabel"
     aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="editAddressModalLabel">افزودن دسته بندی</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form class="row" method="post" data-ajax="true">
                    <div class="col-md-6">
                        @Html.EditorFor(f => f.Name)
                    </div>
                    <div class="col-md-6">
                        <ul>
                            @foreach (var item in Enum.GetNames(typeof(Permissions)))
                            {
                                <li>
                                    <label class="cursor-pointer">
                                        <input name="permissions" value="@item" type="checkbox" />
                                        @item.Replace("_", " ")
                                    </label>
                                </li>
                            }
                        </ul>

                    </div>
                    <div class="col-md-6"></div>
                    <div class="col-md-12 d-flex mt-2 justify-content-end">
                        <submit />
                    </div>
                </form>

            </div>
        </div>
    </div>
</div>

src/EndPoints/DigiLearn.Web/Areas/Admin/Pages/Roles/_Edit.cshtml
@using UserModule.Data.Entities._Enums
@using Microsoft.AspNetCore.Mvc.TagHelpers
@using BTCsalman.Web.TagHelpers
@model BTCsalman.Web.ViewModels.Admin.EditRoleViewModel

<form class="row" method="post" asp-page-handler="Edit" data-ajax="true">
    @Html.HiddenFor(f=>f.RoleId)
    <div class="col-md-6">
        @Html.EditorFor(f => f.Name)
    </div>
    <div class="col-md-6">
        <ul>
            @foreach (var item in Enum.GetNames(typeof(Permissions)))
            {
                <li>
                    <label class="cursor-pointer">
                        <input name="permissions"
                               checked="@(Model.SelectedPermissions.Any(r => r.ToString() == item) ? "checked" : null)" value="@item" type="checkbox"/>
                        @item.Replace("_", " ")
                    </label>
                </li>
            }
        </ul>
    </div>
    <div class="col-md-6"></div>
    <div class="col-md-12 d-flex mt-2 justify-content-end">
        <submit/>
    </div>
</form>