src/EndPoints/DigiLearn.Web/Areas/Admin/Pages/Teachers/Index.cshtml.cs
using CoreModule.Facade.Teacher;
using CoreModule.Query.Teacher._DTOs;
using BTCsalman.Web.Infrastructure.RazorUtils;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BTCsalman.Web.Areas.Admin.Pages.Teachers;

public class IndexModel : BaseRazor
{
    private readonly ITeacherFacade _teacherFacade;

    public IndexModel(ITeacherFacade teacherFacade)
    {
        _teacherFacade = teacherFacade;
    }

    public List<TeacherDto> Teachers { get; set; }
    public async Task OnGet()
    {
        Teachers = await _teacherFacade.GetList();
    }

    public async Task<IActionResult> OnPostToggleStatus(Guid id)
    {
        return await AjaxTryCatch(() => _teacherFacade.ToggleStatus(id));
    }
}

src/EndPoints/DigiLearn.Web/Areas/Admin/Pages/Teachers/Show.cshtml.cs
using CoreModule.Application.Teacher.AcceptRequest;
using CoreModule.Application.Teacher.RejectRequest;
using CoreModule.Facade.Teacher;
using CoreModule.Query.Teacher._DTOs;
using BTCsalman.Web.Infrastructure.RazorUtils;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BTCsalman.Web.Areas.Admin.Pages.Teachers
{
    public class ShowModel : BaseRazor
    {
        private ITeacherFacade _teacherFacade;

        public ShowModel(ITeacherFacade teacherFacade)
        {
            _teacherFacade = teacherFacade;
        }

        public TeacherDto Teacher { get; set; }
        public async Task<IActionResult> OnGet(Guid id)
        {
            var teacher = await _teacherFacade.GetById(id);
            if (teacher == null)
                return RedirectToPage("Index");

            Teacher = teacher;
            return Page();
        }

        public async Task<IActionResult> OnPostAccept(Guid id)
        {
            return await AjaxTryCatch(() => _teacherFacade.AcceptRequest(new AcceptTeacherRequestCommand()
            {
                TeacherId = id
            }));
        }
        public async Task<IActionResult> OnPostReject(Guid id, string description)
        {
            var result = await _teacherFacade.RejectRequest(new RejectTeacherRequestCommand()
            {
                TeacherId = id,
                Description = description
            });
            return RedirectAndShowAlert(result, RedirectToPage("Show", new { id }));
        }
    }
}

src/EndPoints/DigiLearn.Web/Areas/Admin/Pages/Tickets/Show.cshtml.cs
using System.ComponentModel.DataAnnotations;
using Common.Application;
using BTCsalman.Web.Infrastructure;
using BTCsalman.Web.Infrastructure.RazorUtils;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using TicketModule.Core.DTOs.Tickets;
using TicketModule.Core.Services;
using UserModule.Core.Services;

namespace BTCsalman.Web.Areas.Admin.Pages.Tickets
{
    public class ShowModel : BaseRazor
    {
        private readonly ITicketService _ticketService;
        public readonly IUserFacade _userFacade;
        public ShowModel(ITicketService ticketService, IUserFacade userFacade)
        {
            _ticketService = ticketService;
            _userFacade = userFacade;
        }

        public TicketDto Ticket { get; set; }

        [BindProperty]
        [Display(Name = "متن پیام")]
        [Required(ErrorMessage = "{0} را وارد کنید")]
        public string Text { get; set; }
        public async Task<IActionResult> OnGet(Guid id)
        {
            var ticket = await _ticketService.GetTicket(id);
            if (ticket == null )
                return RedirectToPage("Index");


            Ticket = ticket;
            return Page();
        }

        public async Task<IActionResult> OnPost(Guid id)
        {
            var user = await _userFacade.GetUserByPhoneNumber(User.GetPhoneNumber());
            var message = new SendTicketMessageCommand()
            {
                OwnerFullName = $"{user.Name} {user.Family}",
                Text = Text,
                TicketId = id,
                UserId = User.GetUserId()
            };
            var result = await _ticketService.SendMessageInTicket(message);
            return RedirectAndShowAlert(result, RedirectToPage("Show", new { id }));
        }


        public async Task<IActionResult> OnPostCloseTicket(Guid ticketId)
        {
            return await AjaxTryCatch(async () =>
            {
                var ticket = await _ticketService.GetTicket(ticketId);
                if (ticket == null || ticket.UserId != User.GetUserId())
                    return OperationResult.Error("تیکت یافت نشد");

                return await _ticketService.CloseTicket(ticketId);
            });
        }
    }
}

src/EndPoints/DigiLearn.Web/Pages/Blog/Show.cshtml.cs
using BlogModule.Services;
using BlogModule.Services.DTOs.Query;
using CommentModule.Domain;
using CommentModule.Services;
using CommentModule.Services.DTOs;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BTCsalman.Web.Pages.Blog
{
    public class ShowModel : PageModel
    {
        private IBlogService _blogService;
        private ICommentService _commentService;
        public ShowModel(IBlogService blogService, ICommentService commentService)
        {
            _blogService = blogService;
            _commentService = commentService;
        }

        public BlogPostFilterItemDto BlogPost { get; set; }
        public CommentFilterResult CommentFilterResult { get; set; }



        public async Task<IActionResult> OnGet(string slug)
        {
            var article = await _blogService.GetPostBySlug(slug);
            if (article == null)
            {
                return NotFound();
            }
            BlogPost = article;
            CommentFilterResult = await _commentService.GetCommentByFilter(new CommentFilterParams()
            {
                EntityId = article.Id,
                CommentType = CommentType.Article,
            });
            _blogService.AddPostVisit(article.Id);
            return Page();
        }
    }
}

src/EndPoints/DigiLearn.Web/Pages/Profile/Teacher/Courses/Add.cshtml.cs
using System.ComponentModel.DataAnnotations;
using Common.Domain.Utils;
using Common.Domain.ValueObjects;
using CoreModule.Application.Course.Create;
using CoreModule.Domain.Course.Enums;
using CoreModule.Facade.Course;
using CoreModule.Facade.Teacher;
using BTCsalman.Web.Infrastructure;
using BTCsalman.Web.Infrastructure.RazorUtils;
using BTCsalman.Web.Infrastructure.Utils.CustomValidation.IFormFile;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BTCsalman.Web.Pages.Profile.Teacher.Courses;


[ServiceFilter(typeof(TeacherActionFilter))]
[BindProperties]
public class AddModel : BaseRazor
{
    private readonly ICourseFacade _courseFacade;
    private readonly ITeacherFacade _teacherFacade;
    public AddModel(ICourseFacade courseFacade, ITeacherFacade teacherFacade)
    {
        _courseFacade = courseFacade;
        _teacherFacade = teacherFacade;
    }


    [Display(Name = "دسته بندی اصلی")]
    [Required(ErrorMessage = "{0} را وارد کنید")]
    public Guid CategoryId { get; set; }


    [Display(Name = "زیر دسته بندی")]
    [Required(ErrorMessage = "{0} را وارد کنید")]
    public Guid SubCategoryId { get; set; }

    [Display(Name = "عنوان دوره")]
    [Required(ErrorMessage = "{0} را وارد کنید")]
    public string Title { get; set; }


    [Display(Name = "عنوان انگلیسی دوره")]
    [Required(ErrorMessage = "{0} را وارد کنید")]
    public string Slug { get; set; }


    [Display(Name = "توضیحات")]
    [Required(ErrorMessage = "{0} را وارد کنید")]
    [UIHint("Ckeditor4")]
    public string Description { get; set; }


    [Display(Name = "عکس دوره")]
    [Required(ErrorMessage = "{0} را وارد کنید")]
    [FileImage(ErrorMessage = "عکس نامعتبر است")]
    public IFormFile ImageFile { get; set; }

    [Display(Name = "ویدئو معرفی دوره")]
    [FileType("mp4", ErrorMessage = "ویدبئو معرفی نامعتبر است")]
    public IFormFile? VideoFile { get; set; }


    [Display(Name = "قیمت (0=رایگان(")]
    [Required(ErrorMessage = "{0} را وارد کنید")]
    public int Price { get; set; }

    [Display(Name = "سطح دوره")]
    [Required(ErrorMessage = "{0} را وارد کنید")]
    public CourseLevel CourseLevel { get; set; }

    public void OnGet()
    {
    }

    public async Task<IActionResult> OnPost()
    {
        var teacher = await _teacherFacade.GetByUserId(User.GetUserId());

        var result = await _courseFacade.Create(new CreateCourseCommand()
        {
            Status = CourseActionStatus.Pending,
            TeacherId = teacher!.Id,
            Slug = Slug.ToSlug(),
            Title = Title,
            ImageFile = ImageFile,
            VideoFile = VideoFile,
            CourseLevel = CourseLevel,
            CategoryId = CategoryId,
            Description = Description,
            SeoData = new SeoData(Title, Title, Title, null),
            Price = Price,
            SubCategoryId = SubCategoryId
        });
        return RedirectAndShowAlert(result, RedirectToPage("Index"));
    }
}

src/EndPoints/DigiLearn.Web/Pages/Profile/Teacher/Courses/Index.cshtml.cs
using CoreModule.Facade.Course;
using CoreModule.Facade.Teacher;
using CoreModule.Query.Course._DTOs;
using BTCsalman.Web.Infrastructure;
using BTCsalman.Web.Infrastructure.RazorUtils;
using Microsoft.AspNetCore.Mvc;

namespace BTCsalman.Web.Pages.Profile.Teacher.Courses;


[ServiceFilter(typeof(TeacherActionFilter))]
public class IndexModel : BaseRazorFilter<CourseFilterParams>
{
    private readonly ICourseFacade _courseFacade;
    private readonly ITeacherFacade _teacherFacade;
    public IndexModel(ICourseFacade courseFacade, ITeacherFacade teacherFacade)
    {
        _courseFacade = courseFacade;
        _teacherFacade = teacherFacade;
    }

    public CourseFilterResult FilterResult { get; set; }
    public async Task OnGet()
    {
        var teacher = await _teacherFacade.GetByUserId(User.GetUserId());
        FilterParams.TeacherId = teacher?.Id;
        FilterResult = await _courseFacade.GetCourseFilter(FilterParams);
    }
}

src/EndPoints/DigiLearn.Web/Pages/Profile/Teacher/Courses/Sections/Add.cshtml.cs
using System.ComponentModel.DataAnnotations;
using CoreModule.Application.Course.Sections.AddSection;
using CoreModule.Facade.Course;
using BTCsalman.Web.Infrastructure;
using BTCsalman.Web.Infrastructure.RazorUtils;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BTCsalman.Web.Pages.Profile.Teacher.Courses.Sections;


[ServiceFilter(typeof(TeacherActionFilter))]
[BindProperties]
public class AddModel : BaseRazor
{
    private ICourseFacade _courseFacade;

    public AddModel(ICourseFacade courseFacade)
    {
        _courseFacade = courseFacade;
    }


    [Display(Name = "عنوان")]
    [Required(ErrorMessage = "{0} را وارد کنید")]
    public string Title { get; set; }

    [Display(Name = "ترتیب نمایش")]
    [Required(ErrorMessage = "{0} را وارد کنید")]
    public int DisplayOrder { get; set; }


  
    public void OnGet()
    {
    }

    public async Task<IActionResult> OnPost(Guid courseId)
    {
        var result = await _courseFacade.AddSection(new AddCourseSectionCommand()
        {
            Title = Title,
            DisplayOrder = DisplayOrder,
            CourseId = courseId,
        });

        return RedirectAndShowAlert(result, RedirectToPage("Index", new { courseId }));
    }
}

src/EndPoints/DigiLearn.Web/Pages/Profile/Teacher/Courses/Sections/Episodes/Add.cshtml.cs
using System.ComponentModel.DataAnnotations;
using CoreModule.Application.Course.Episodes.Add;
using CoreModule.Facade.Course;
using BTCsalman.Web.Infrastructure;
using BTCsalman.Web.Infrastructure.RazorUtils;
using BTCsalman.Web.Infrastructure.Utils.CustomValidation.IFormFile;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BTCsalman.Web.Pages.Profile.Teacher.Courses.Sections.Episodes;


[ServiceFilter(typeof(TeacherActionFilter))]
[BindProperties]
public class AddModel : BaseRazor
{
    private readonly ICourseFacade _courseFacade;

    public AddModel(ICourseFacade courseFacade)
    {
        _courseFacade = courseFacade;
    }

    [Display(Name = "عنوان")]
    [Required(ErrorMessage = "{0} را وارد کنید")]
    public string Title { get; set; }

    [Display(Name = "عنوان انگلیسی")]
    [Required(ErrorMessage = "{0} را وارد کنید")]
    public string EnglishTitle { get; set; }

    [Display(Name = "مدت زمان")]
    [Required(ErrorMessage = "{0} را وارد کنید")]
    [RegularExpression(@"^([0-9]{1}|(?:0[0-9]|1[0-9]|2[0-3])+):([0-5]?[0-9])(?::([0-5]?[0-9])(?:.(\d{1,9}))?)?$", ErrorMessage = "لطفا زمان را با فرمت درست وارد کنید")]
    public TimeSpan TimeSpan { get; set; }

    [Display(Name = "ویدئو")]
    [FileType("mp4", ErrorMessage = "ویدئو نامعتبر است")]
    [Required(ErrorMessage = "{0} را وارد کنید")]
    public IFormFile VideoFile { get; set; }

    [Display(Name = "فایل ضمیمه")]
    [FileType("rar", ErrorMessage = "فایل ضمیمه نامعتبر است")]
    public IFormFile? AttachmentFile { get; set; }

    [Display(Name = "این قسمت رایگان است")]
    public bool IsFree { get; set; }

    public void OnGet()
    {
    }

    public async Task<IActionResult> OnPost(Guid courseId, Guid sectionId)
    {
        var result = await _courseFacade.AddEpisode(new AddCourseEpisodeCommand()
        {
            Title = Title,
            AttachmentFile = AttachmentFile,
            VideoFile = VideoFile,
            IsActive = false,
            CourseId = courseId,
            EnglishTitle = EnglishTitle,
            TimeSpan = TimeSpan,
            SectionId = sectionId,
            IsFree = IsFree
        });

        return RedirectAndShowAlert(result, RedirectToPage("../Index", new { courseId }));
    }
}

src/EndPoints/DigiLearn.Web/Pages/Profile/Teacher/Courses/Sections/Index.cshtml.cs
using CoreModule.Facade.Course;
using CoreModule.Facade.Teacher;
using CoreModule.Query.Course._DTOs;
using BTCsalman.Web.Infrastructure;
using BTCsalman.Web.Infrastructure.RazorUtils;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BTCsalman.Web.Pages.Profile.Teacher.Courses.Sections;


[ServiceFilter(typeof(TeacherActionFilter))]
public class IndexModel : BaseRazor
{
    private ICourseFacade _courseFacade;
    private readonly ITeacherFacade _teacherFacade;
    public IndexModel(ICourseFacade courseFacade, ITeacherFacade teacherFacade)
    {
        _courseFacade = courseFacade;
        _teacherFacade = teacherFacade;
    }

    public CourseDto Course { get; set; }
    public async Task<IActionResult> OnGet(Guid courseId)
    {
        var course = await _courseFacade.GetCourseById(courseId);
        var teacher = await _teacherFacade.GetByUserId(User.GetUserId());

        if (course == null || course.TeacherId != teacher!.Id)
        {
            return RedirectToPage("../Index");
        }

        Course = course;
        return Page();
    }
}

src/EndPoints/DigiLearn.Web/Pages/Profile/Tickets/Show.cshtml.cs
using System.ComponentModel.DataAnnotations;
using Common.Application;
using BTCsalman.Web.Infrastructure;
using BTCsalman.Web.Infrastructure.RazorUtils;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using TicketModule.Core.DTOs.Tickets;
using TicketModule.Core.Services;
using UserModule.Core.Services;

namespace BTCsalman.Web.Pages.Profile.Tickets
{
    public class ShowModel : BaseRazor
    {
        private ITicketService _ticketService;
        private IUserFacade _userFacade;
        public ShowModel(ITicketService ticketService, IUserFacade userFacade)
        {
            _ticketService = ticketService;
            _userFacade = userFacade;
        }

        public TicketDto Ticket { get; set; }


        [BindProperty]
        [Display(Name = "متن پیام")]
        [Required(ErrorMessage = "{0} را وارد کنید")]
        public string Text { get; set; }
        public async Task<IActionResult> OnGet(Guid ticketId)
        {
            var ticket = await _ticketService.GetTicket(ticketId);
            if (ticket == null || ticket.UserId != User.GetUserId())
                return RedirectToPage("Index");


            Ticket = ticket;
            return Page();
        }

        public async Task<IActionResult> OnPost(Guid ticketId)
        {
            var user = await _userFacade.GetUserByPhoneNumber(User.GetPhoneNumber());
            var message = new SendTicketMessageCommand()
            {
                OwnerFullName = $"{user.Name} {user.Family}",
                Text = Text,
                TicketId = ticketId,
                UserId = User.GetUserId()
            };
            var result = await _ticketService.SendMessageInTicket(message);
            return RedirectAndShowAlert(result, RedirectToPage("Show", new { ticketId }));
        }


        public async Task<IActionResult> OnPostCloseTicket(Guid ticketId)
        {
            return await AjaxTryCatch(async () =>
            {
                var ticket = await _ticketService.GetTicket(ticketId);
                if (ticket == null || ticket.UserId != User.GetUserId())
                    return OperationResult.Error("تیکت یافت نشد");

                return await _ticketService.CloseTicket(ticketId);
            });
        }
    }
}

src/EndPoints/DigiLearn.Web/Areas/Admin/Pages/Teachers/Index.cshtml
@page "{handler?}"
@using CoreModule.Domain.Teacher.Enums
@model BTCsalman.Web.Areas.Admin.Pages.Teachers.IndexModel
@{
    ViewData["title"] = "مدیریت مدرسین";
    ViewData["selected"] = "teachers";
}
<div class="card ">
    <div class="table-responsive card-body p-0 mb-0">
        <table class="table table-bordered table-hover mb-0 data-table">
            <thead>
                <tr>
                    <th>نام کاربری</th>
                    <th>نام و نام خانوادگی</th>
                    <th>شماره تلفن</th>
                    <th>وضعیت</th>
                    <th>عملیات</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Teachers)
                {
                    <tr>
                        <td>@item.UserName</td>
                        <td>@item.User.Name @item.User.Name</td>
                        <td>@item.User.PhoneNumber</td>
                        <td>
                            @switch (@item.Status)
                            {
                                case TeacherStatus.Active:
                                <label class="badge bg-success">فعال</label>
                                    break;
                                case TeacherStatus.Inactive:
                                    <label class="badge bg-danger">غیرفعال</label>

                                    break;

                                case TeacherStatus.Pending:
                                    <label class="badge bg-primary">درحال برسی</label>

                                    break;
                            }
                        </td>
                        <td>
                            @if (item.Status == TeacherStatus.Active)
                            {
                                <Question class="btn btn-danger" url="@Url.Page("Index", "toggleStatus", new { id = item.Id })">
                                    غیرفعال سازی

                                </Question>
                            }
                            else if (item.Status == TeacherStatus.Inactive)
                            {
                                <Question class="btn btn-success" url="@Url.Page("Index", "toggleStatus", new { id = item.Id })">
                                    فعال سازی
                                </Question>
                            }
                            <a class="btn btn-primary" asp-page="Show" asp-route-id="@item.Id">نمایش</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

src/EndPoints/DigiLearn.Web/Areas/Admin/Pages/Teachers/Show.cshtml
@page "{id}/{handler?}"
@using UserModule.Core
@using CoreModule.Application._Utilities
@using Common.Application.DateUtil
@using CoreModule.Domain.Teacher.Enums
@model BTCsalman.Web.Areas.Admin.Pages.Teachers.ShowModel
@{
    ViewData["title"] = "نمایش اطلاعات مدرس";
    ViewData["selected"] = "teachers";
}
<h2>اطلاعات مدرس</h2>
@if (Model.Teacher.Status == TeacherStatus.Pending)
{
    <Question class="btn btn-success" url="@Url.Page("Show","Accept",new {id=Model.Teacher.Id})">تایید درخواست</Question>
}
<div class="card card-body mt-1">
    <img src="@UserModuleDirectories.GetUserAvatar(Model.Teacher.User.Avatar)" style="max-width: 150px" class="mb-2" />
    <div class="row">
        <div class="col-md-6">نام کاربری : @Model.Teacher.UserName</div>
        <div class="col-md-6">نام و نام خانوادگی : @Model.Teacher.User.Name @Model.Teacher.User.Family</div>

        <div class="col-md-6">شماره تلفن : @Model.Teacher.User.PhoneNumber</div>

        <div class="col-md-6">ایمیل : @Model.Teacher.User.Email</div>

        <div class="col-md-6">تاریخ ثبت نام : @Model.Teacher.CreationDate.ToPersianDateTime()</div>

        <div class="col-md-6">
            وضعیت :
            @switch (Model.Teacher.Status)
            {
                case TeacherStatus.Active:
                    <label class="badge bg-success">فعال</label>
                    break;
                case TeacherStatus.Inactive:
                    <label class="badge bg-danger">غیرفعال</label>

                    break;

                case TeacherStatus.Pending:
                    <label class="badge bg-primary">درحال برسی</label>

                    break;
            }
        </div>
        <div class="col-md-12">رزومه : <a href="@CoreModuleDirectories.GetCvFile(Model.Teacher.CvFileName)" target="_blank">نمایش</a></div>
    </div>
</div>
@if (Model.Teacher.Status == TeacherStatus.Pending)
{
    <div class="card card-body mt-2">
        <form method="post" asp-page-handler="Reject">
            <textarea class="form-control" name="description" placeholder="دلیل رد درخواست"></textarea>
            <button class="btn btn-danger mt-1" onclick="return confirm('آیا از انجام عملیات اطمینان دارید')">رد درخواست</button>
        </form>
    </div>
}